name : js_pr
on : [ pull_request ]

jobs :
  test :
    uses : Wandalen/wTools/.github/workflows/StandardJsCommon.yml@master
    with :
      matrix : '{ "os" : [ "ubuntu-latest", "windows-latest", "macos-latest" ], "node-version" : [ "14.x" ] }'
      group : standard_pull_request_${{ github.head_ref }}

